name: MTMT Publikációs listaellenőrzés
description: Publikációs listák karbantartására szolgáló űrlap
labels: "MTMT listaellenőrzés"
body:
  - type: input
    id: name
    attributes:
      label: Név
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: E-mail cím
    validations:
      required: true
  - type: input
    id: MTMT
    attributes:
      label: MTMT azonosító
    validations:
      required: true 
  - type: dropdown
    id: keres
    attributes:
      label: Kérés típusa
      options:
        - Lista ellenőrzés egyetemi pályázathoz
        - Lista ellenőrzés MTA doktora pályázathoz
        - Idézőfrissítés (WOS, Scopus)
    validations:
      required: true
  - type: input
    id: palyazat
    attributes:
      label: Pályázat beadásának határideje
      description: "pl.: 2022-05-28"
    validations:
      required: true 
  - type: textarea
    id: megjegyzes
    attributes:
      label: Megjegyzés
    validations:
      required: true
